### ISSUE TITLE
Python module 'langchain' seems to be missing

### ISSUE THREAD

**Issue by ConfusedAlex** [nextcloud/llm#4]
### Steps to reproduce
1. Install Nextcloud AIO
2. Install [Large Language Model App](https://apps.nextcloud.com/apps/llm)
3. Activate Nextcloud Asisstant and ask it something
4. Witness error

### Expected behavior
The needed python modules should be installed

### Actual behavior 
The python module 'langchain' seems to be missing

### Host OS 
NixOS

#### Nextcloud AIO version 
7.2.1

#### Current channel 
latest

#### Other valuable info 
`Traceback (most recent call last): File "/var/www/html/custom_apps/llm/src-py/index.py", line 3, in <module> from chains.formalize import FormalizeChain File "/var/www/html/custom_apps/llm/src-py/chains/formalize.py", line 2, in <module> from langchain import BasePromptTemplate, PromptTemplate ModuleNotFoundError: No module named 'langchain' `

**Comment by szaimen** [comment]
![Screenshot_20230917_080053_Brave](https://github.com/nextcloud/llm/assets/42591237/747b4624-55eb-4031-99d2-a2bf105369a8)

Apparently musl is not supported @marcelklehr ?

**Comment by marcelklehr** [comment]
I'm couldn't find information if GPT4All requires GNU lib C or not, but I suspect it does so I added that to the README. The error above doesn't seem to be because of lib c problems, though, but rather about the installation.

@ConfusedAlex Could you run occ maintenance:repair and check the nextcloud log for errors afterwards?

**Comment by ConfusedAlex** [comment]
While running `occ maintenance:repair` I got this Error:

`{"reqId":"j5xTUu9qVDvgszvgZOnq","level":3,"time":"2023-09-17T09:01:36+00:00","remoteAddr":"","user":"--","app":"llm","method":"","url":"--","message":"Failed to install python dependencies: PATH=/var/www/html/custom_apps/llm/python/bin:$PATH VIRTUAL_ENV=/var/www/html/custom_apps/llm/python POETRY_CACHE_DIR=/var/www/html/custom_apps/llm/python/.cache /var/www/html/custom_apps/llm/python/bin/poetry  install --no-root returned Installing dependencies from lock file\n\nPackage operations: 4 installs, 0 updates, 0 removals\n\n  • Installing numexpr (2.8.4)\n\n  ChefBuildError\n\n  Backend 'setuptools.build_meta' is not available.\n\n  at /var/www/html/custom_apps/llm/python/venvs/poetry/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare\n      143│\n      144│                 error = ChefBuildError(\"\\n\\n\".join(message_parts))\n      145│\n      146│             if error is not None:\n    → 147│                 raise error from None\n      148│\n      149│             return path\n      150│\n      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:\n\nNote: This error originates from the build backend, and is likely not a problem with poetry but with numexpr (2.8.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 \"numexpr (==2.8.4)\"'.","userAgent":"--","version":"27.1.0.7","data":{"app":"llm"},"id":"6506c277479e4"}`

**Comment by marcelklehr** [comment]
@szaimen

**Comment by marcelklehr** [comment]
That seems to be a problem with poetry, will publish a fix

**Comment by oparoz** [comment]
I was getting a similar error in the logs when trying to use the LLM, but it was a red herring, all I needed to do was to install the virtual environment. Maybe it will work for you @ConfusedAlex?

`# apt install python3.10-venv`

**Comment by marcelklehr** [comment]
with the alpine container ie. Nextcloud AIO, things inevitably fail for various reasons.

**Comment by sevmonster** [comment]
FYI, this issue is indeed that NomicAI does not publish prebuilt packages for GPT4All, as seen [here](https://pypi.org/simple/gpt4all/), and they no longer provide buildable tarballs since it seems their build method has changed; you need to download and compile the backend first before compiling the Python bindings that target that specific backend.

If musl/Alpine support was something people were interested in, either NomicAI would need to be convinced to start shipping a musl-compatible build, or it would need to be built by Nextcloud.

Users should be able to build their own and put it in the venv and it should just work. Untested since I no longer care enough to try it myself :upside_down_face:
